In [5]:
import numpy as np

In [6]:
l=[1,2,3,4,5]
print(l)

[1, 2, 3, 4, 5]


In [7]:
arr=np.arange(1,6)

In [8]:
print(arr)

[1 2 3 4 5]


In [9]:
c=2

Element wise operations
1.Arthemetic Operations

In [10]:
# l+c  #error
print(arr+c)
print(arr-c)
print(arr*2)

[3 4 5 6 7]
[-1  0  1  2  3]
[ 2  4  6  8 10]


2.Relational operation

In [11]:
l==c # list is not equal to int 

False

In [12]:
arr==c # elememt wise checking 

array([False,  True, False, False, False])

In [13]:
# l>c # list cannot be compared with int

In [14]:
arr>c

array([False, False,  True,  True,  True])

In [15]:
arr<c

array([ True, False, False, False, False])

In [16]:
arr>>c

array([0, 0, 0, 1, 1])

In [17]:
arr<<c

array([ 4,  8, 12, 16, 20])

In [18]:
arr&c

array([0, 2, 2, 0, 0])

In [19]:
a=np.array([8,9,10,11,12])
print(a)

[ 8  9 10 11 12]


In [20]:
arr+a

array([ 9, 11, 13, 15, 17])

In [21]:
#Arthemetic Operator
print(arr+a)
print(arr-a)
print(arr/a)
print(arr//a)
print(arr%a)
print(arr*a)

[ 9 11 13 15 17]
[-7 -7 -7 -7 -7]
[0.125      0.22222222 0.3        0.36363636 0.41666667]
[0 0 0 0 0]
[1 2 3 4 5]
[ 8 18 30 44 60]


In [22]:
#Bitwise operator
print(arr>>a)
print(arr<<a)
print(arr&a)
print(arr|a)
print(arr^a)

[0 0 0 0 0]
[  256  1024  3072  8192 20480]
[0 0 2 0 4]
[ 9 11 11 15 13]
[ 9 11  9 15  9]


In [23]:
#Relational operator
print(arr>a)
print(arr<a)
print(arr==a)
print(arr!=a)
print(arr>=a)
print(arr<=a)

[False False False False False]
[ True  True  True  True  True]
[False False False False False]
[ True  True  True  True  True]
[False False False False False]
[ True  True  True  True  True]


In [24]:
# Membership Operator
print(arr in a)
print(arr not in a)
print(c in arr)
print(c  not in arr)

False
True
True
False


**Broadcasting**

In [26]:
a1=np.array([5,2])
print(a1)
print(a1.shape)


[5 2]
(2,)


In [28]:
a2=np.array([[1,2],[3,4],[3,4]])
print(a2,end='\n\n\n')
print(a2.shape)

[[1 2]
 [3 4]
 [3 4]]


(3, 2)


In [29]:
print(a1+a2)


[[6 4]
 [8 6]
 [8 6]]


In [30]:
a3=np.array([[[10,20,30],[40,50,60]],[[1,2,3],[4,5,6]],[[7,8,9],[4,2,3]]])
print(a3,end='\n\n\n')
print(a3.shape)

[[[10 20 30]
  [40 50 60]]

 [[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [ 4  2  3]]]


(3, 2, 3)


In [32]:
a4=np.array([[2,4,6]])
print(a4.shape)

(1, 3)


In [ ]:
a4=np.array([[2,4,6]])
print(a4.shape)

In [33]:
print(a3+a4)

[[[12 24 36]
  [42 54 66]]

 [[ 3  6  9]
  [ 6  9 12]]

 [[ 9 12 15]
  [ 6  6  9]]]


In [34]:
a5=np.array([[5,6,7,8]])
print(a5.shape)

(1, 4)


**Assignment**