In [18]:
import numpy as np

In [19]:
np.arange(10,50,5)  #return type is int

array([10, 15, 20, 25, 30, 35, 40, 45])

In [20]:
np.arange(50)   # it gives all the numers within a range.return type is array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [21]:
range(50)    #return type is object or function.it gives only start number and ending number

range(0, 50)

In [22]:
np.linspace(start=100,stop=105,num=20)     #parameter start num,end num,number of elements to generate

array([100.        , 100.26315789, 100.52631579, 100.78947368,
       101.05263158, 101.31578947, 101.57894737, 101.84210526,
       102.10526316, 102.36842105, 102.63157895, 102.89473684,
       103.15789474, 103.42105263, 103.68421053, 103.94736842,
       104.21052632, 104.47368421, 104.73684211, 105.        ])

In [23]:
np.linspace(start=100,stop=105)

array([100.        , 100.10204082, 100.20408163, 100.30612245,
       100.40816327, 100.51020408, 100.6122449 , 100.71428571,
       100.81632653, 100.91836735, 101.02040816, 101.12244898,
       101.2244898 , 101.32653061, 101.42857143, 101.53061224,
       101.63265306, 101.73469388, 101.83673469, 101.93877551,
       102.04081633, 102.14285714, 102.24489796, 102.34693878,
       102.44897959, 102.55102041, 102.65306122, 102.75510204,
       102.85714286, 102.95918367, 103.06122449, 103.16326531,
       103.26530612, 103.36734694, 103.46938776, 103.57142857,
       103.67346939, 103.7755102 , 103.87755102, 103.97959184,
       104.08163265, 104.18367347, 104.28571429, 104.3877551 ,
       104.48979592, 104.59183673, 104.69387755, 104.79591837,
       104.89795918, 105.        ])

In [24]:
np.linspace(start=100,stop=105,num=8,retstep=True)   #retstep=return step which will give the step value internally calculated.

(array([100.        , 100.71428571, 101.42857143, 102.14285714,
        102.85714286, 103.57142857, 104.28571429, 105.        ]),
 np.float64(0.7142857142857143))

In [25]:
np.linspace(start=2,stop=10,num=5)   #returns array of equally spaced floating number.

array([ 2.,  4.,  6.,  8., 10.])

In [26]:
np.linspace(2,10,5)

array([ 2.,  4.,  6.,  8., 10.])

In [27]:
np.zeros((4,))

array([0., 0., 0., 0.])

In [28]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.ones((4,))

array([1., 1., 1., 1.])

In [30]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [31]:
np.eye(3,3)    #identity matrix(squared matrix),eye(N=rows,M=cols) it takes M as N defaultly

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
np.eye(3)   #defaultly it takes second value,because of eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
np.eye(3,4)   #non squared identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])