In [1]:
import numpy as np
import numpy.random as rnd

In [2]:
rnd.randint(1,101)               #randint=random integers .it supports for only integer.

82

In [3]:
rnd.randint(1,101,(5,))    #it gives the list of elements based on given value

array([69, 18, 69, 31, 16], dtype=int32)

In [4]:
rnd.randint(1,101,(5,3))   #low,high,shape

array([[89, 68, 66],
       [20, 13, 36],
       [16, 18, 45],
       [10, 27, 45],
       [15, 56, 64]], dtype=int32)

In [5]:
rnd.seed(34)            #seed not changes the random numbers.
arr1=rnd.randint(1,101,(5,3))
print(arr1)


[[34 86 69]
 [36 70 12]
 [79 30 19]
 [30 90 30]
 [21 97 63]]


In [6]:
print(arr1[2,2])    #it gives the value based on the address.

19


In [7]:
print(arr1[2])
print(arr1[4,2])   
print(arr1[-1,-1])
print(arr1[0,0])
print(arr1[::2])
print(arr1[::,1])
print(arr1[::,[0,2]])  #or
print(arr1[::,::2])
print(arr1[::-1,::2])  #or
print(arr1[::-1,[0,2]])



[79 30 19]
63
63
34
[[34 86 69]
 [79 30 19]
 [21 97 63]]
[86 70 30 90 97]
[[34 69]
 [36 12]
 [79 19]
 [30 30]
 [21 63]]
[[34 69]
 [36 12]
 [79 19]
 [30 30]
 [21 63]]
[[21 63]
 [30 30]
 [79 19]
 [36 12]
 [34 69]]
[[21 63]
 [30 30]
 [79 19]
 [36 12]
 [34 69]]


1 [79,30,19]
2 [63]
3 [34,69]
4 [[34 86 69]
  [79 30 19]
  [21 97 63]]
5 [86 70 30 90 97]
6[[34  69]
  [36  12]
  [79  19]
  [30  30]
  [21  63]]
7[[21 63]
 [30 30]
 [79 19]
 [36 12]
 [34 69]]

In [8]:
#creating 3D
rnd.seed(34)
arr2=rnd.randint(1,101,(3,2,4))   #low,high,shape
print(arr2)

[[[34 86 69 36]
  [70 12 79 30]]

 [[19 30 90 30]
  [21 97 63  6]]

 [[21 52 20 86]
  [22 64 73 43]]]


In [9]:
#EXAMPLES
print(arr2[2])
print(arr2[2,1,2])
print(arr2[-2,-1,-2])




[[21 52 20 86]
 [22 64 73 43]]
73
63


In [10]:
l=['kiccha','sudeep','badsha','Abhinaya chakravarthi']
print(l)

['kiccha', 'sudeep', 'badsha', 'Abhinaya chakravarthi']


In [11]:
rnd.choice(l)

np.str_('sudeep')

In [12]:
rnd.choice(l,(3,))

array(['kiccha', 'kiccha', 'badsha'], dtype='<U21')

In [13]:
rnd.choice(l,(3,),p=[0.20,0.05,0.35,0.40])  #using probability factor

array(['Abhinaya chakravarthi', 'badsha', 'badsha'], dtype='<U21')

In [14]:
#to avoid the duplicates we use replace=False
rnd.choice(l,(3,),replace=False)

array(['kiccha', 'sudeep', 'Abhinaya chakravarthi'], dtype='<U21')

In [15]:
l1=[[10,20],[30,40]]
print(l1)
l2=[[10,20],[30,40,50]]
print(l2)

[[10, 20], [30, 40]]
[[10, 20], [30, 40, 50]]


In [16]:
a2=np.array(l1)

In [17]:
l2[1][0]    #nested=square brackets,sibling can have differen elements

30

In [18]:
a2[1,0] #for array we accec values like this,we can give comma seperation,and sibling must have same number of elements.

np.int64(30)

In [19]:
rnd.rand()

0.42760915369682506

In [20]:

rnd.rand(3,2)

array([[0.99808623, 0.7037764 ],
       [0.01118787, 0.54254899],
       [0.20498485, 0.86036881]])

In [21]:
rnd.randn()

1.1559002459321077

In [22]:
rnd.seed(45)
n1=rnd.rand(5)
np.mean(n1)


np.float64(0.46835252086527285)

In [23]:
np.std(n1)

np.float64(0.30532348590889036)

In [24]:
np.mean(n1).round()

np.float64(0.0)

In [25]:
np.std(n1).round()

np.float64(0.0)

In [26]:
l=[100,200,300,400,500,89.9]
print(l)

[100, 200, 300, 400, 500, 89.9]


In [27]:
rnd.choice(l)     #it supports for all the type of inputs

np.float64(200.0)