In [1]:
import numpy as np

In [3]:
#create a 1-D  array with the size of 5 elements
a1=np.array([940,80,90,30,25,78,78,90,65,54,890,87])
print(a1)


[940  80  90  30  25  78  78  90  65  54 890  87]


In [4]:
a2=np.copy(a1)
print(a2)

[940  80  90  30  25  78  78  90  65  54 890  87]


In [5]:
a1[0]=500
print(a1)
print(a2)

[500  80  90  30  25  78  78  90  65  54 890  87]
[940  80  90  30  25  78  78  90  65  54 890  87]


In [ ]:
a3=a2.view()   
print(a3)     

[940  80  90  30  25  78  78  90  65  54 890  87]


In [ ]:
a2[9::]=0   
print(a2)
print(a3)

[940  80  90  30  25  78  78  90  65   0   0   0]
[940  80  90  30  25  78  78  90  65   0   0   0]


In [8]:
print(a1)

[500  80  90  30  25  78  78  90  65  54 890  87]


In [ ]:
a1.shape    #we using factors

(12,)

In [10]:
np.reshape(a1,(2,6))

array([[500,  80,  90,  30,  25,  78],
       [ 78,  90,  65,  54, 890,  87]])

In [ ]:
np.reshape(a1,(3,4))  # it convertion one dimention to any dimention,vewing in view and it is flexible

array([[500,  80,  90,  30],
       [ 25,  78,  78,  90],
       [ 65,  54, 890,  87]])

In [12]:
np.reshape(a1,(4,3))

array([[500,  80,  90],
       [ 30,  25,  78],
       [ 78,  90,  65],
       [ 54, 890,  87]])

In [13]:
np.reshape(a1,(6,2))

array([[500,  80],
       [ 90,  30],
       [ 25,  78],
       [ 78,  90],
       [ 65,  54],
       [890,  87]])

In [ ]:
np.reshape(a1,(3,2,2))

array([[[500,  80],
        [ 90,  30]],

       [[ 25,  78],
        [ 78,  90]],

       [[ 65,  54],
        [890,  87]]])

In [16]:
r1=np.reshape(a1,(2,3,2,1))
print(r1)

[[[[500]
   [ 80]]

  [[ 90]
   [ 30]]

  [[ 25]
   [ 78]]]


 [[[ 78]
   [ 90]]

  [[ 65]
   [ 54]]

  [[890]
   [ 87]]]]


In [ ]:
np.reshape(r1,shape=-1)   #1-D array,#it can covert one dimension to another,it has high flexibility.

array([500,  80,  90,  30,  25,  78,  78,  90,  65,  54, 890,  87])

In [20]:
r1=np.reshape(a1,(2,3,2))
print(r1)

[[[500  80]
  [ 90  30]
  [ 25  78]]

 [[ 78  90]
  [ 65  54]
  [890  87]]]


In [ ]:
r2=np.reshape(r1,shape=-1)
print(r2)
#r2 is a view of r1

[500  80  90  30  25  78  78  90  65  54 890  87]


In [22]:
r1[1,2,1]
r1[-1,-1,-1]

np.int64(87)

In [24]:
r1[-1,-1,-1]=999
print(r1,end='\n\n\n')
print(r2)

[[[500  80]
  [ 90  30]
  [ 25  78]]

 [[ 78  90]
  [ 65  54]
  [890 999]]]


[500  80  90  30  25  78  78  90  65  54 890 999]
