In [19]:
import numpy as np

In [20]:
a1=np.arange(2,21,2)

In [21]:
a2=np.reshape(a1,(2,5))

In [22]:
a1[0]=900
print(a1,end='\n\n\n')
print(a2)

[900   4   6   8  10  12  14  16  18  20]


[[900   4   6   8  10]
 [ 12  14  16  18  20]]


**ravel()**  #view is output

In [23]:
a3=np.array([[2,4,6,8,10],[12,14,16,18,20]])
print(a3)

[[ 2  4  6  8 10]
 [12 14 16 18 20]]


In [24]:
r1=np.ravel(a3)   #it can convert only multidimention to 1-D #viewing in view itself
print(r1)

[ 2  4  6  8 10 12 14 16 18 20]


In [25]:
r1[0]=222
print(a3,end="\n\n\n")
print(r1)

[[222   4   6   8  10]
 [ 12  14  16  18  20]]


[222   4   6   8  10  12  14  16  18  20]


flatten()   #output is shallow copy

In [26]:
a4=np.array([[2,4,6,8,10],[12,14,16,18,20]])
print(a4)

[[ 2  4  6  8 10]
 [12 14 16 18 20]]


In [27]:
r2=a4.flatten()
print(r2)

[ 2  4  6  8 10 12 14 16 18 20]


In [28]:
r2[0]=567
print(a4,end="\n\n\n")
print(r2)

[[ 2  4  6  8 10]
 [12 14 16 18 20]]


[567   4   6   8  10  12  14  16  18  20]


scalar array

In [29]:
#1-D array
x=np.array([9,8,7])
print(x)
print(x.ndim)


[9 8 7]
1


In [30]:
#0-D array  
x=np.array([88])     
print(x)
print(x.ndim)

[88]
1


In [36]:
np.full((6,),200)

array([200, 200, 200, 200, 200, 200])

In [32]:
np.full((3,2),200)

array([[200, 200],
       [200, 200],
       [200, 200]])

where()

In [42]:
a=np.array([6,3,2,8,2,5,9,5,9])
print(a)

[6 3 2 8 2 5 9 5 9]


In [43]:
a==5

array([False, False, False, False, False,  True, False,  True, False])

In [44]:
np.where(a==5) #index of the true values

(array([5, 7]),)

In [45]:
np.where(a==5,'yes','no')

array(['no', 'no', 'no', 'no', 'no', 'yes', 'no', 'yes', 'no'],
      dtype='<U3')

In [46]:
print(a)

[6 3 2 8 2 5 9 5 9]


In [47]:
a>5

array([ True, False, False,  True, False, False,  True, False,  True])

In [48]:
a[a>5]

array([6, 8, 9, 9])