In [3]:
import numpy as np     #numpy stands for numerical python

In [4]:
l=[2,33,45,22,25,12]
print(l)
print(type(l))

[2, 33, 45, 22, 25, 12]
<class 'list'>


to create a array we have to pass,list of elements.

In [5]:
a1=np.array(l)
print(a1)
print(type(a1))

[ 2 33 45 22 25 12]
<class 'numpy.ndarray'>


In [6]:
l=[[23,22,45,21],[56,87,88,45],[45,34,22,34]]
print(l)

[[23, 22, 45, 21], [56, 87, 88, 45], [45, 34, 22, 34]]


In [7]:
a2=np.array(l)
print(a2)

[[23 22 45 21]
 [56 87 88 45]
 [45 34 22 34]]


In [8]:
print(a2.dtype)
print(a2.itemsize)   #it gives in bytes format for single element
print(a2.size)       #it gives total number of elements
print(a2.nbytes)     #it gives bytes for total elements

int64
8
12
96


In [ ]:
print(a1.dtype)
print(a1.itemsize)   
print(a1.size)       
print(a1.nbytes) 
print(a2.shape)    #it will say how many elements present in each bracket.
print(a1.shape)

int64
8
6
48
(3, 4)


In [18]:
a1.ndim   #number of dimention

1

In [19]:
a2.ndim   #it gives dimension of the array

2

In [21]:
l=[56,78,98.6]
print(l)

[56, 78, 98.6]


In [ ]:
np.array(l)   #it gives in float beacause float is more powerfull datatype compared to int.

array([56. , 78. , 98.6])

In [ ]:
l=[56,78,98.6,5+7j]    #it gives in complex datatype because complex datatype is more powerfull compared to int and float
print(l)
np.array(l)

[56, 78, 98.6, (5+7j)]


array([56. +0.j, 78. +0.j, 98.6+0.j,  5. +7.j])

In [25]:
l=[56,78,98.6,5+7j,'python']    #it gives in their original datatype
np.array(l)

array(['56', '78', '98.6', '(5+7j)', 'python'], dtype='<U64')

In [ ]:
l=[56,78,98.6,5+7j,'python','python']    #it supporting duplicate elements also
np.array(l)

array(['56', '78', '98.6', '(5+7j)', 'python', 'python'], dtype='<U64')

In [ ]:
l=[56,78,98.6,5+7j,'python','python']    #list is supports indexing and slicing
np.array(l)
print(l[0])
print(l[-1])
print(l[::-1])
print(l[::2])

56
python
['python', 'python', (5+7j), 98.6, 78, 56]
[56, 98.6, 'python']


In [ ]:
arr=np.array(l)   #array also supports indexing and slicing.
print(arr)
arr[0]

['56' '78' '98.6' '(5+7j)' 'python' 'python']


np.str_('56')

In [ ]:
print(arr[0])     #array also supports indexing and slicing.
print(arr[-1])
print(arr[::-1])
print(arr[::2])

56
python
['python' 'python' '(5+7j)' '98.6' '78' '56']
['56' '98.6' 'python']


In [ ]:
arr[0]=78965443    #array is not supports for insertion and deletion .it supports fo updation.
print(arr)

['78965443' '78' '98.6' '(5+7j)' 'python' 'python']


concatination and mutiplication is not supports in array.